on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAProxy website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.example.com'
          rules_file_name: '.github/workflows/rules.tsv'
          issue_title: 'custom security scanning'
